nelmio_cors:
    defaults:
        allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$', '*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
    paths:
        '^/': null